[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "Cython==0.29.33",
    "numpy==1.24.0",
    "Flask==2.3.3",
    "scikit-learn==1.3.0",
    "pandas==1.5.3"
]
